config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :questions
  resources :categories
  resources :associations, :path => 'a'
  devise_for :users
  devise_scope :user do
	 get "/login" => "devise/sessions#new"
	end
  resources :pages , :path => 'p' do
    collection { post :sort}
  end
  root to: "information#home"
  get 'information/home'
  get 'information/most_viewed_pages'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/association.rb
class Association < ApplicationRecord
end

app/controllers/associations_controller.rb
class AssociationsController < ApplicationController
  before_action :set_association, only: [:show, :edit, :update, :destroy]

  # GET /associations
  # GET /associations.json
  def index
    @associations = Association.all
  end

  # GET /associations/1
  # GET /associations/1.json
  def show
    @page = Page.find(@association.pageID)
    redirect_to page_path(@page.slug)
  end

  # GET /associations/new
  def new
    @association = Association.new
  end

  # GET /associations/1/edit
  def edit
  end

  # POST /associations
  # POST /associations.json
  def create
    @association = Association.new(association_params)

    respond_to do |format|
      if @association.save
        format.html { redirect_to @association, notice: 'Association was successfully created.' }
        format.json { render :show, status: :created, location: @association }
      else
        format.html { render :new }
        format.json { render json: @association.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /associations/1
  # PATCH/PUT /associations/1.json
  def update
    respond_to do |format|
      if @association.update(association_params)
        format.html { redirect_to @association, notice: 'Association was successfully updated.' }
        format.json { render :show, status: :ok, location: @association }
      else
        format.html { render :edit }
        format.json { render json: @association.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /associations/1
  # DELETE /associations/1.json
  def destroy
    @association.destroy
    respond_to do |format|
      format.html { redirect_to associations_url, notice: 'Association was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_association
      @association = Association.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def association_params
      params.require(:association).permit(:pagename, :pageID)
    end
end

app/helpers/associations_helper.rb
module AssociationsHelper
end

app/views/associations/_form.html.erb
<%= form_for(association) do |f| %>
  <% if association.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(association.errors.count, "error") %> prohibited this association from being saved:</h2>

      <ul>
      <% association.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pagename %>
    <%= f.text_field :pagename %>
  </div>

  <div class="field">
    <%= f.label :pageID %>
    <%= f.number_field :pageID %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/associations/edit.html.erb
<h1>Editing Association</h1>

<%= render 'form', association: @association %>

<%= link_to 'Show', @association %> |
<%= link_to 'Back', associations_path %>

app/views/associations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Associations</h1>

<table>
  <thead>
    <tr>
      <th>Pagename</th>
      <th>Pageid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @associations.each do |association| %>
      <tr>
        <td><%= association.pagename %></td>
        <td><%= association.id %></td>
        <td><%= association.pageID %></td>
        <td><%= link_to 'Show', association %></td>
        <td><%= link_to 'Edit', edit_association_path(association) %></td>
        <td><%= link_to 'Destroy', association, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Association', new_association_path %>

app/views/associations/new.html.erb
<h1>New Association</h1>

<%= render 'form', association: @association %>

<%= link_to 'Back', associations_path %>

app/views/associations/show.html.erb
<p id="notice"><%= notice %></p>
<%= @page.slug%>
<p>
  <strong>Pagename:</strong>
  <%= @association.pagename %>
</p>

<p>
  <strong>Pageid:</strong>
  <%= @association.pageID %>
</p>

<%= link_to 'Edit', edit_association_path(@association) %> |
<%= link_to 'Back', associations_path %>